### ISSUE TITLE
configuring UTC vs TAI in meinberg

### ISSUE THREAD

**Issue by ghost** [chalmers-revere/opendlv-platform-rhino#14]
38s issue

**Comment by chrberger** [comment]
Changed "Timescale" from "Arbitrary" to "PTP Standard (TAI)"

**Comment by chrberger** [comment]
* Reverted "Timescale" from "PTP Standard (TAI)" to "Arbitrary"
* Changed profile to "Default P2P IEEE1588-2008 --> removed 38s offset
